#
# Copyright (c) 2021-2025 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.github.io.
#
# SPDX-License-Identifier: CC-BY-4.0
#
MD013:
  code_blocks : false
  tables : false
MD033: false
MD037: false
MD046: false
