#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.github.io.
#
# SPDX-License-Identifier: Apache-2.0
#
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        types: [css]
